@startuml
:Cliente: -- (Reservar Vuelo)
:Cliente: -- (Pedir Azucar)
:Cliente: -- (Pedir Producto)
:Cliente: -- (Cancelar)
(Cancelar) --> (Devolver Dinero) : <<include>>
(Pedir Producto) --> (Devolver Dinero) : <<include>>

@enduml