@startuml
(Sacar Dinero) <<+ Solicitud Hecha>>
note "description condicion <<historia sospechosa>> punto de extension: solicitud hecha" as N2
(Retener Tarjeta)
(Sacar Dinero) --> N2 : <<Extend>>
(Retener Tarjeta) --> N2

@enduml