@startuml
:New Actor: -- (Identificarse)
:New Actor: -- (Pagar)
:New Actor: -- (Elegir Mensajero)
:New Actor: -- (Confirmar)
(Pagar) <|-- (Pagar Con Tarjeta)
(Pagar) <|-- (Pagar Con Transferencia)
(Identificarse) <.. (Registrarse)
@enduml